version: "3.9"
name: mvc
services:
  nginx_mvc:
    container_name: nginx_mvc
    image: nginx:1.17.8
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www
    links:
      - php_mvc
  php_mvc:
    container_name: php_mvc
    build: ./php
    working_dir: /var/www
    volumes:
      - ../:/var/www
